local function restartUI(withMsg)
  SendUIMessage({ source = "ev-nui", app = "main", action = "restart" });
  if withMsg then
    TriggerEvent("DoLongHudText", "You can also use 'ui-r' as a shorter version to restart!")
  end
  TriggerScreenblurFadeOut(100.0)
  TriggerEvent('closeInventoryGui')
  TriggerEvent('ev-banking:ResetUI')
  TriggerEvent('ev-radio:ResetUI')
  TriggerEvent('ev-menu:ResetUI')
  TriggerEvent('ev-interact:ResetUI')
  TriggerEvent('ev-mdt:ResetUI')
  TriggerEvent('ev-ui:restartUI')
  TriggerEvent('menu:menuexit')
  TriggerEvent('clothing:close')
  exports['ev-interface']:showInteraction("Restarting UI .")
  Wait(1000)
  exports['ev-interface']:showInteraction("Restarting UI ..")
  Wait(1000)
  exports['ev-interface']:showInteraction("Restarting UI ...")
  Wait(1000)
  exports['ev-interface']:showInteraction("UI Successfully Restarted")
  Wait(1000)
  exports['ev-interface']:hideInteraction()
  --TriggerEvent("ev-hud:initHud")
  initHud()
  TriggerEvent("ev-hud:restarted")
  SendUIMessage({ app = "hud", data = { display = true }, source = "ev-nui" })
  local cj = exports["police"]:getCurrentJob()
end
RegisterCommand("ev-hud:restart", function() restartUI(true) end, false)
RegisterCommand("ui-r", function() restartUI() end, false)
RegisterNetEvent("ev-hud:server-restart")
AddEventHandler("ev-hud:server-restart", restartUI)