function StationaryPed(info)
    LoadModel(info.model)
    local ped = CreatePed(4, info.model, vector3(info.x, info.y, info.z - 1.0), info.h, false, false)
    SetModelAsNoLongerNeeded(info.model)
    SetPedDefaultComponentVariation(ped)
    SetEntityHeading(ped, info.h)
    SetEntityInvincible(ped, true)
    FreezeEntityPosition(ped, true)
    SetBlockingOfNonTemporaryEvents(ped, true)
    SetPedFleeAttributes(ped, 0, 0)
    SetPedCombatAttributes(ped, 17, 1)
    SetPedSeeingRange(ped, 0.0)
    SetPedHearingRange(ped, 0.0)
    SetPedAlertness(ped, 0)
    SetPedKeepTask(ped, true)
    return ped
end